lr: 0.001
min_lr: 0.001
weight_decay: 0.00001 # l2 norm
# patience: 3
es_patience: 4 #patience for early stop

dropout_rate: 0.2
num_blocks: 2
num_heads: 2

## item embedding
embedding_dim: 64

num_neg: 1280